#!/usr/bin/env python3
import re, glob, os, html, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def slugify(s):
    t = re.sub(r'[^0-9A-Za-z_]+', '-', s.lower())
    t = t.strip('-')
    return t[:60]

def strip_tags(s):
    return html.unescape(re.sub(r'<[^>]+>', '', s)).strip()

entries = []
for f in sorted(glob.glob(os.path.join(ROOT, "sections", "*.html"))):
    slug = os.path.splitext(os.path.basename(f))[0]
    s = open(f, encoding="utf-8").read()
    # section number, read off the eyebrow only: lesson bodies cross-reference other sections
    m = re.search(r'class="lesson-eyebrow"[^>]*>(.*?)</p>', s, re.S)
    m = re.search(r'Section\s+(\d+)', m.group(1)) if m else None
    num = m.group(1) if m else ""
    # title
    m = re.search(r'<h1 class="lesson-title">(.*?)</h1>', s, re.S)
    title = strip_tags(m.group(1)) if m else slug
    # keywords from the "You'll learn" objectives box
    m = re.search(r'class="objectives".*?<ul>(.*?)</ul>', s, re.S)
    keywords = []
    if m:
        keywords = [strip_tags(k) for k in re.findall(r'<li>(.*?)</li>', m.group(1), re.S) if strip_tags(k)]
    # headings (h2 + h3) inside .prose; drop leading section number like runtime
    headings = []
    for hm in re.finditer(r'<h[23]([^>]*)>(.*?)</h[23]>', s, re.S):
        text = strip_tags(hm.group(2))
        text = re.sub(r'^\s*\d+\s*', '', text).strip()
        if not text:
            continue
        # a hand-written id wins, like at runtime (assignHeadingIds skips headings that have one)
        idm = re.search(r'\bid="([^"]+)"', hm.group(1))
        headings.append({"t": text, "id": idm.group(1) if idm else slugify(text)})
    entries.append({"slug": slug, "num": num, "title": title,
                    "keywords": keywords, "headings": headings})

out = "/* Auto-generated by tools/build-search-index.py — do not edit by hand. */\n"
out += "window.SEARCH_INDEX = " + json.dumps(entries, ensure_ascii=False, indent=0).replace("\n", "") + ";\n"
dst = os.path.join(ROOT, "assets", "search-index.js")
open(dst, "w", encoding="utf-8").write(out)
print("wrote", dst, f"({len(entries)} sections, {sum(len(e['headings']) for e in entries)} headings indexed)")
